language: generic
sudo: true

services:
  - docker

env:
  matrix:
    - TAG=ubuntu-2004
    - TAG=debian-11
    - TAG=centos-7

script:
  - make build
  - make test

before_deploy:
  - export DOCKER_CONFIG="${HOME}/.docker"
  - mkdir -p "$DOCKER_CONFIG"
  openssl aes-256-cbc -K $encrypted_2dd25a6cb1a7_key -iv $encrypted_2dd25a6cb1a7_iv -in config.json.enc -out .docker/config.json -d

deploy:
  provider: script
  skip_cleanup: true
  script: make push
  on:
    branch: master
