FROM <%= ENV.fetch 'BASE_IMAGE' %>

ENV GIT_FROM_RPMFORGE_PKG <%= ENV['GIT_FROM_RPMFORGE_PKG'] || '""' %>

ARG DEBIAN_FRONTEND=noninteractive

ADD platform/<%= ENV.fetch 'PLATFORM' %> /platform
RUN /platform/install-deps.sh

RUN git config --global user.email "builder@aptible.com" \
 && git config --global user.name "Builder"

RUN wget -O ruby-install-0.6.0.tar.gz https://github.com/postmodern/ruby-install/archive/v0.6.0.tar.gz \
 && tar -xzvf ruby-install-0.6.0.tar.gz \
 && cd ruby-install-0.6.0/ \
 && make install \
 && cd .. \
 && rm -rf ruby-install-0.6.0 \
 && rm ruby-install-0.6.0.tar.gz

ENV RUBY_VERSION 2.6.9
RUN /platform/install-ruby.sh && rm -rf "/usr/local/src/ruby-${RUBY_VERSION}"

RUN gem install bundler

ENV OMNIBUS_VERSION 5.5.0
RUN gem install omnibus --version "$OMNIBUS_VERSION"
